force-app/main/default/objects/Product_Plan__c/Product_Plan__c.object-meta.xml
<CustomObject>
    <label>Product Plan</label>
    <nameField>
        <label>Product Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Plan__c/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <description>This value determines the ATM fee in other currencies.</description>
    <label>ATM Fee in Other Currencies</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>This value determines the car replacement cost.</description>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>This value determines the cost per calender month.</description>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This value determines the banking Country.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This value determines the banking product plan.</description>
    <inlineHelpText>Select the banking plan.</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductController.cls
public with sharing class ProductController {
    /**
     * @Description : Fetches product pricing details based on product type and country.
     * @User Story  : Case Study - Senior Salesforce Engineer Task 1.
     * @author      : Arpitha A Gowda
     * @return      : A single Product_Plan__c record or null if no match is found.
     */
   @AuraEnabled(cacheable=true)
    public static Product_Plan__c getProductDetails(String product, String country) {
        if (String.isBlank(product) || String.isBlank(country)) {
            return null;
        }
        try {
            List<Product_Plan__c> results = [SELECT Cost_per_Calendar_Month__c, ATM_Fee_in_Other_Currencies__c,  Card_Replacement_Cost__c
                FROM Product_Plan__c  WHERE Product__c = :product AND Home_Country__c = :country WITH SECURITY_ENFORCED LIMIT 1
            ];
            return results.isEmpty() ? null : results[0];

        } catch (Exception e) {
            throw new AuraHandledException('Error retrieving product information: ' + e.getMessage());
        }
    }
}