force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This value determines the customer’s home country.</description>
    <inlineHelpText>Select the customer’s home country</inlineHelpText>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This value determines the customer’s active banking plan.</description>
    <inlineHelpText>Select the customer’s current banking plan.</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/UUID__c.field-meta.xml
<CustomField>
    <fullName>UUID__c</fullName>
    <description>This value determines the External system unique number.</description>
    <inlineHelpText>This value determines the External system unique number.</inlineHelpText>
    <externalId>true</externalId>
    <label>UUID</label>
    <length>254</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product_Plan__c/Product_Plan__c.object-meta.xml
<CustomObject>
    <label>Product Plan</label>
    <nameField>
        <label>Product Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Plan</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Plan__c/fields/ATM_Fee_in_Other_Currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_Other_Currencies__c</fullName>
    <description>This value determines the ATM fee in other currencies.</description>
    <label>ATM Fee in Other Currencies</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <description>This value determines the car replacement cost.</description>
    <label>Card Replacement Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Cost_per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_per_Calendar_Month__c</fullName>
    <description>This value determines the cost per calender month.</description>
    <label>Cost per Calendar Month</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>This value determines the banking Country.</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Home_Country</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Plan__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>This value determines the banking product plan.</description>
    <inlineHelpText>Select the banking plan.</inlineHelpText>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Home_Country.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>ES</fullName>
    </customValue>
    <customValue>
        <fullName>FR</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>UK</fullName>
    </customValue>
    <masterLabel>Home Country</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <customValue>
        <fullName>Standard</fullName>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContactAPI.cls
@RestResource(urlMapping='/v1/ContactProductDetails/*')
  /**
 * @Description : REST API to expose Contact and Product Rate information to N26 external systems.
 * @User Story  : Case Study - Senior Salesforce Engineer Task 2.
 * @Author      : Arpitha A Gowda
 */
global with sharing class ContactAPI {

    @HttpGet
    global static void doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        //Extract UUID from the URL path
        String uuid = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);     
        try {
            //Fetching Contact by UUID
            Contact con = [SELECT Product__c, Home_Country__c FROM Contact WHERE UUID__c = :uuid LIMIT 1];          
            //Fetching matching product Information from Product_plan__c
            Product_Plan__c Fee = [SELECT Cost_per_Calendar_Month__c, ATM_Fee_in_Other_Currencies__c,  Card_Replacement_Cost__c
                                   FROM Product_plan__c 
                                   WHERE Product__c = :con.Product__c 
                                   AND Home_Country__c = :con.Home_Country__c 
                                   LIMIT 1];  
            //JSON response
            res.responseBody = Blob.valueOf(JSON.serialize(Fee));
            res.statusCode = 200;
            
        } catch (Exception e) {
            res.statusCode = 404;
            res.responseBody = Blob.valueOf('{"error": "Record not found"}');
        }
    }
}